baseURL = "https://lectupedia.netlify.app"
title = "Lectupedia"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
languageCode = "es-co"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
disqusShortname = "lectupedia"
enableGitInfo = true
pluralizeListTitles = false
summaryLength = 35
removePathAccents = true

[menu]

  # [[menu.nav]]
  #   name = "English Site"
  #   url = "../en/"
  #   weight = 1

  [[menu.nav]]
    name = "Archivo"
    url = "/archive/"
    weight = 2

  [[menu.nav]]
    name = "Temas"
    url = "/tags/"
    weight = 3

  # [[menu.nav]]
  # name = "Acerca de"
  # url = "/acerca-de/"
  # weight = 4

  # [[menu.nav]]
  # name = "RSS"
  # url = "/index.xml"
  # weight = 5

  # [[menu.nav]]
  #   name = "Blog"
  #   url = "/post/"
  #   weight = 6

[languages]
  [languages.es]
  languageName = "Español"
  weight = 1

  [languages.fr]
  languageName = "Français"
  weight = 3

  [languages.en]
    languageName = "English"
    weight = 2
    description = "Let's talk about reading."
    homeMetaContent = "Let's talk about reading."
    footer = "2020· Lectupedia by [Andrés Peña](https://www.linkedin.com/in/andreseduardop/) is licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.en) <img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1' /><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1' /><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1' />"

    # [[languages.en.menu.nav]]
    #   name = "Sitio en Español"
    #   url = "../es/"
    #   weight = 1

    [[languages.en.menu.nav]]
      name = "Archive"
      url = "/archive/"
      weight = 2

    [[languages.en.menu.nav]]
      name = "Topics"
      url = "/tags/"
      weight = 3

[taxonomies]
  # El parametro "tags" (del FM de los <articulos>.md) es invocado en la plantilla single de <articulos>
  # Al cambiar "tags" el layout single fallará.
  tag = "tags"

[permalinks]
  # post = "/:filename/"
  archive = "/:filename/"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  
  [[related.indices]]
    name = "tags"
    weight = 100

    [[related.indices]]
    name = "date"
    weight = 50

[imaging]
  quality = 85

[params]
  description = "Hablemos sobre lectura."
  homeMetaContent = "Hablemos sobre lectura."
  footer = "2020· Lectupedia, por [Andrés Peña](https://www.linkedin.com/in/andreseduardop/), está disponible bajo licencia [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.es) <img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1' /><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1' /><img style='height:22px!important;margin-left:3px;vertical-align:text-bottom;' src='https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1' />"
  footer2 = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  dateFormat = "Jan 2, 2006"
  author = "Andrés Peña"
  images = "images/site-feature-image.jpg"
  # codePenUser = "someUser"
  katex = false
  darkThemeAsDefault = false
  hideHeaderLinks = false
  search = true
  customCss = [ "css/custom_01.css" ]
  # customJs = [ "js/custom_01.js", "js/custom_02.js" ]
  facebook = "Lectupedia"
  twitter = "andreseduardop_"
  linkedin = "andreseduardop"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"

  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xHTML = false

  [markup.highlight]
    codeFences = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
