baseURL = "https://example.com"
languageCode = "es-co"
defaultContentLanguage = "es"
title = "Lectupedia"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"
enableGitInfo = true

[languages.es]
languageName = "Spanish"
weight = 1

[languages.en]
languageName = "English"
weight = 2
description = "Let's talk about reading."
homeMetaContent = "Let's talk about reading."
footer = "2020- Lectupedia by [Andrés Peña](https://www.linkedin.com/in/andreseduardop/) is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

[taxonomies]
# El parametro "tags" (del FM de los <articulos>.md) es invocado en la plantilla single de <articulos>
# TODO: Cambiar por "topics" en inglés
tag = "tags"

[permalinks]
# post = "/:filename/"
archivo = "/:filename/"

[imaging]
quality = 99

[params]
description = "Hablemos sobre lectura."
homeMetaContent = "Todo acerca de la lectura."
footer = "2020- Lectupedia por [Andrés Peña](https://www.linkedin.com/in/andreseduardop/) está disponible bajo licencia [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.es)."
dateFormat = "Jan 2, 2006"
codePenUser = "someUser"
katex = true
darkThemeAsDefault = false
hideHeaderLinks = false
search = true
customCss = [ "css/custom_01.css", "css/custom_02.css" ]
customJs = [ "js/custom_01.js", "js/custom_02.js" ]

[[menu.nav]]
name = "Inicio"
url = "/"
weight = 1

[[menu.nav]]
name = "Archivo"
url = "/archivo/"
weight = 2

[[menu.nav]]
name = "Temas"
url = "/tags/"
weight = 3

[[menu.nav]]
name = "Acerca de"
url = "/acerca-de/"
weight = 4

# [[menu.nav]]
# name = "RSS"
# url = "/index.xml"
# weight = 5

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2
