[[redirects]]
	from = "/es/*"
	to = "/es/404.html"
	status = 404

[[redirects]]
	from = "/en/*"
	to = "/en/404.html"
	status = 404

[[redirects]]
	from = "/*"
	to = "/en/404.html"
	status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src https: 'self' 'unsafe-inline';"
		X-DNS-Prefetch-Control = "on"

[build.environment]
HUGO_VERSION = "0.140.3"
TZ = "America/Bogota"

[build]
publish = "public"
command = "hugo --gc --minify"
